In [2]:
"""
动态RNN方法，非固定序列长度方法
"""
import tensorflow as tf
import numpy as np

In [3]:
n_step = 2
n_input = 3
n_neurons = 5

In [4]:
x=tf.placeholder(tf.float32,[None,n_step,n_input])
seq_length=tf.placeholder(tf.int32,[None])#改变序列长度
x_seqs=tf.unstack(tf.transpose(x,[1,0,2]))
basic_cell=tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
outseq,state=tf.nn.dynamic_rnn(basic_cell,x,dtype=tf.float32,sequence_length=seq_length)
output=tf.transpose(outseq,[1,0,2])


For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.


Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API


Instructions for updating:
Use tf.cast instead.


Instructions for updating:
Colocations handled automatically by placer.


In [5]:
xbatch=np.array(range(30))
xbatch=np.reshape(xbatch,newshape=[5,2,3])

In [10]:
init=tf.global_variables_initializer()
length_seq=[2,1,2,1,2]

In [11]:
with tf.Session() as sess:
    init.run()
    outval = output.eval(feed_dict={
        x: xbatch,
        seq_length:length_seq
    })
print(outval)

[[[-0.9469192  -0.7369663   0.15045689 -0.6445312   0.45017895]
  [-1.         -0.9999999   0.98983705  0.5528362  -0.99501574]
  [-1.         -1.          0.99992937  0.96478266 -0.9999953 ]
  [-1.         -1.          0.9999995   0.99777114 -1.        ]
  [-1.         -1.          1.          0.9998611  -1.        ]]

 [[-0.999868   -0.99988097  0.5916105  -0.16594942 -0.94411266]
  [ 0.          0.          0.          0.          0.        ]
  [-1.         -1.          0.9999808   0.91167814 -1.        ]
  [ 0.          0.          0.          0.          0.        ]
  [-1.         -1.          1.          0.99962765 -1.        ]]]
