In [1]:
%matplotlib inline

In [2]:
import numpy as np


In [3]:
x=np.ones(shape=(3,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
x.ndim

2

In [5]:
from keras.datasets import mnist
(trian_image,train_labels),(test_image,test_labels)=mnist.load_data()

Using TensorFlow backend.


In [6]:
train_labels.ndim

1

In [7]:
train_image=trian_image
trian_image.ndim

3

In [8]:
trian_image.shape

(60000, 28, 28)

In [9]:
train_image.dtype

dtype('uint8')

In [1]:
import cupy as cp
cp.ones((256,256))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [2]:
cp.zeros((256,256))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])