In [1]:
"""
多标签
单标签
映射替换
对 高中低（标签的文字意义暗示大小）进行编码
"""



import numpy as np
from sklearn.preprocessing import LabelBinarizer,MultiLabelBinarizer
%matplotlib inline

In [2]:
feature=np.array(
    [
        "japan",
        "china",
        "america",
        "china",
        "britain"
    ]
)
one_hot=LabelBinarizer()

In [4]:
tmp = one_hot.fit_transform(feature)
tmp


array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0]])

In [5]:
one_hot.classes_

array(['america', 'britain', 'china', 'japan'], dtype='<U7')

In [6]:
tmp=one_hot.inverse_transform(tmp)
tmp


array(['japan', 'china', 'america', 'china', 'britain'], dtype='<U7')

In [15]:
import pandas as pd
pd.set_option('display.unicode.ambiguous_as_wide', True)
pd.set_option('display.unicode.east_asian_width', True)


tmp=pd.get_dummies(feature)
print(tmp)


   america  britain  china  japan
0        0        0      0      1
1        0        0      1      0
2        1        0      0      0
3        0        0      1      0
4        0        1      0      0


In [16]:
feature = np.array(
    [
        ("japan", "china"),
        ("china", "britain"),
        ("america", "britain"),
        ("china", "america"),
        ("britain", "japan"),
    ]
)
one_hot_multi = MultiLabelBinarizer()
tmp = one_hot_multi.fit_transform(feature)
tmp

array([[0, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [18]:
dataframe=pd.DataFrame(
    {
        "score":["low","median","low","high"]
    }
)

In [19]:
scale_mapper={
    "low":0,
    "median":1,
    "high":2
}

In [21]:
print(dataframe.describe())

       score
count      4
unique     3
top      low
freq       2


In [22]:
print(dataframe)

    score
0     low
1  median
2     low
3    high


In [23]:
tmp=dataframe["score"].replace(scale_mapper)
print(tmp)

0    0
1    1
2    0
3    2
Name: score, dtype: int64


In [24]:
from sklearn.feature_extraction import DictVectorizer
datafeature=[
    {"red":2,"gren":1},
    {"red":3,"gren":7},
    {"red":8,"blue":9},
    {"red":2,"blue":5}
]

In [25]:
dicvector=DictVectorizer(sparse=False)
feature=dicvector.fit_transform(datafeature)

In [26]:
feature

array([[0., 1., 2.],
       [0., 7., 3.],
       [9., 0., 8.],
       [5., 0., 2.]])

In [27]:
print(dicvector.get_feature_names())

['blue', 'gren', 'red']
