In [1]:
"""
l1,l2 正则化
交互式
特征转换
转换器
异常值：椭圆检测，四分位差检测
特征离散化
"""

import numpy as np
import sklearn

In [8]:
features=np.random.randint(10,size=(3,4))
print(features)

[[1 1 2 8]
 [9 6 9 1]
 [6 9 2 8]]


In [10]:
from sklearn.preprocessing import Normalizer
normalizer=Normalizer(norm='l2')
features=normalizer.transform(features)
print(features)

[[0.11952286 0.11952286 0.23904572 0.95618289]
 [0.63799308 0.42532872 0.63799308 0.07088812]
 [0.44112877 0.66169316 0.14704292 0.5881717 ]]


In [11]:
from sklearn.preprocessing import PolynomialFeatures
features=[
    [2,3],
    [2,3],
    [2,3]
]
poly_interaction=PolynomialFeatures(degree=2,include_bias=False)
poly_interaction.fit_transform(features)

array([[2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.]])

In [12]:
"""
不包含x1 * x2 项
"""
poly_interaction=PolynomialFeatures(degree=2,include_bias=False,interaction_only=True)
poly_interaction.fit_transform(features)

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])

In [13]:
features=np.array(
    [
        [2,3],
        [2,3],
        [2,3],
    ]
)

In [14]:
def add_ten(x):
    return x+10
from sklearn.preprocessing import FunctionTransformer
ten_transform = FunctionTransformer(add_ten)
ten_transform.transform(features)

E:\DEEPENV\lib\site-packages\sklearn\preprocessing\_function_transformer.py:97: FutureWarning: The default validate=True will be replaced by validate=False in 0.22.
  "validate=False in 0.22.", FutureWarning)


array([[12, 13],
       [12, 13],
       [12, 13]])

In [16]:
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs
features,_=make_blobs(
    n_samples=10,
    n_features=2,
    centers=1,
    random_state=1
)
print(features)

[[-1.83198811  3.52863145]
 [-2.76017908  5.55121358]
 [-1.61734616  4.98930508]
 [-0.52579046  3.3065986 ]
 [ 0.08525186  3.64528297]
 [-0.79415228  2.10495117]
 [-1.34052081  4.15711949]
 [-1.98197711  4.02243551]
 [-2.18773166  3.33352125]
 [-0.19745197  2.34634916]]


In [17]:
features[0,0]=1000
features[0,1]=1000
outlier_dectort=EllipticEnvelope(contamination=.1)#污染指数，异常值在整体值中的比例
outlier_dectort.fit(features)
outlier_dectort.predict(features)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [21]:
from sklearn.preprocessing import Binarizer
age=np.array([
    [6],
    [12],
    [24],
    [35],
    [80]
])
binarizer=Binarizer(18)
bage=binarizer.transform(age)
bage

array([[0],
       [0],
       [1],
       [1],
       [1]])

In [22]:
np.digitize(age,bins=[20,30,60],right=True)#是否包含右界

array([[0],
       [0],
       [1],
       [2],
       [3]], dtype=int64)

In [23]:
features=np.array([
    [1.1,11.1],
    [2.1,12.1],
    [3.1,13.1],
    [np.nan,14.1],
]
)
features[~np.isnan(features).any(axis=1)]

array([[ 1.1, 11.1],
       [ 2.1, 12.1],
       [ 3.1, 13.1]])